### ISSUE TITLE
图片贴搭配主机论坛不能用，是不让外链了嘛

### ISSUE THREAD

**Issue by ulifuqiang** [master-of-forums/master-of-forums#14]
![微信截图_20220126123548](https://user-images.githubusercontent.com/25083314/151104584-636d6fbd-b4d6-4a72-b00c-07f8fa3d98ed.png)

**Comment by niu12503** [comment]
同问？

**Comment by upsups** [comment]
[论坛大师](https://github.com/master-of-forums/master-of-forums)新增了图床，请 **重新安装** 或 **等待自动更新**。
