### ISSUE TITLE
loc左边显示主题的怎么不显示了  一直刷不出来

### ISSUE THREAD

**Issue by zhouguangyou1994** [master-of-forums/master-of-forums#16]
如题

**Comment by upsups** [comment]
因为 API 域名被 DNS 污染了，请将翻墙模式改为：**全局模式** 或 **绕过中国大陆IP模式**

**Comment by Meilinhost** [comment]
> 由于API域名被DNS污染了，请将翻墙模式改为：**全局模式**或**绕过中国大陆IP模式**

大佬api域名是多少 我是GFW模式
