### ISSUE TITLE
大佬有考虑过增加黑名单屏蔽吗

### ISSUE THREAD

**Issue by FreyFei** [master-of-forums/master-of-forums#18]
dz自带的屏蔽太蠢了，屏蔽完了还能看到帖子，最好是屏蔽完了帖子不显示，也不现实折叠，点评也不显示，网上找了个脚本可以屏蔽但是这些和点评的标志都还在挺难受的

**Comment by upsups** [comment]
假如A屏蔽了B，B与C在一个主题中交流，A打开这个主题看到C一个人在自说自话。岂不是很怪异？
