### ISSUE TITLE
能否加个自动去除mjj空间里的diy_style的css效果功能

### ISSUE THREAD

**Issue by HackerYunen** [master-of-forums/master-of-forums#3]
有时候查看一些MJJ的空间时候总是有人估计添加css导致页面空白，需要手动删除，怪烦人的。

希望可以考虑加上这个功能，感觉挺实用的。

**Comment by HackerYunen** [comment]
另外，根据c大的回复：https://hostloc.com/thread-881330-1-1.html
91ai.net 并不是官方站，烦请作者去掉下，以免造成不必要的麻烦

**Comment by upsups** [comment]
1. 每个自定义空间的CSS代码不尽相同，无法统一去除每个自定义空间的自定义样式
2. 是官方站

**Comment by HackerYunen** [comment]
>1.每个自定义空间的CSS代码不尽相同，无法统一去除每个自定义空间的自定义样式

只需要去掉个人首页的`<style id="diy_style">...</style>`标签即可。

>2.是官方站

![image](https://user-images.githubusercontent.com/31438247/134477567-62c592df-0d8a-447a-b66a-8c90a5a20363.png)
出处：https://hostloc.com/thread-881330-1-1.html

**Comment by upsups** [comment]
1. 添加好了
2. 他在说谎
