### ISSUE TITLE
能加入对pcbeta的支持么

### ISSUE THREAD

**Issue by coderstory** [master-of-forums/master-of-forums#4]
https://bbs.pcbeta.com/viewthread-1904572-1-1.html

这个网站有反屏蔽广告  直接 display:none之后 直接atler弹出警告

**Comment by upsups** [comment]
搞定，请重新安装[论坛大师](https://github.com/master-of-forums/master-of-forums)。

**Comment by coderstory** [comment]
```
if (typeof alert === 'function') {
      unsafeWindow.alert = () => {};
    }
```
实测 alert 是被去掉了


但是
```
#postlist .a_pt {
      display: none !important;
    }
```

这个class  我是没在html中找到

我现在是把.container隐藏了 但会留下空白.
这些随机名字的id和class 看着就蛋疼

![QQ截图20210927151539](https://user-images.githubusercontent.com/11525359/134861829-7b85474e-c16a-4904-9fc2-446014cb09ee.png)

**Comment by coderstory** [comment]
```
 for (let i = 0; i < 10; i++) {
      setTimeout(() => {
        unsafeWindow.r9aeadS = () => {};
      }, i * 50);
    }
```

不知道这个是啥  
估计也是随机名

**Comment by hishis** [comment]
[论坛大师](https://github.com/master-of-forums/master-of-forums)的广告拦截功能是对[ABP](https://adblockplus.org/)的补充，而不是替代品。

**Comment by upsups** [comment]
[论坛大师](https://github.com/master-of-forums/master-of-forums)的广告拦截功能是对[ABP](https://adblockplus.org/)的补充，而不是替代品。

代码`unsafeWindow.r9aeadS = () => {};`只在[草榴社區](https://www.t66y.com/)生效。

**Comment by coderstory** [comment]
公然发福利呀
