### ISSUE TITLE
请问能否加入其乐社区论坛

### ISSUE THREAD

**Issue by sunete** [master-of-forums/master-of-forums#5]
其乐社区（原蒸汽动力社区） <https://keylol.com/>

论坛里面一些帖子目录看起来很不方便

比如这个帖子 <https://keylol.com/t307370-1-1> 目录在最顶端不方便查看，文章也没有展开的选项，希望目录能在侧边展开

可能工作量有点大，不知道能否适配一下？谢谢。

![image](https://user-images.githubusercontent.com/45954867/135046600-7c5da4b9-d92c-442f-b053-8b8d9dbb4e00.png)

**Comment by upsups** [comment]
不好搞啊

**Comment by sunete** [comment]
不好搞就算了，平时看帖子遇到这样的不多
