### ISSUE TITLE
建议每日签到自动申请任务的时候，跳过“站点推广任务”

### ISSUE THREAD

**Issue by Marukon** [master-of-forums/master-of-forums#6]
这个是DZ论坛的默认任务，ID是1，希望每日签到的时候，可以自动跳过这个任务。

**Comment by upsups** [comment]
我不明白

**Comment by Marukon** [comment]
就是点击“每日签到”按钮的时候
![1](https://user-images.githubusercontent.com/6285343/135756710-eeb4ea55-6d0f-420e-b635-de2592379adc.png)
会自动申请下面的任务：
![2](https://user-images.githubusercontent.com/6285343/135756730-6df36b6c-aa08-4ca5-95ed-838a4c3edc29.png)
建议不要自动申请这个任务。

**Comment by upsups** [comment]
- 我已修复这个问题，你重新安装[旧版](https://greasyfork.org/zh-CN/scripts/400250)即可；
- 这里是[新版](https://github.com/master-of-forums/master-of-forums)仓库。你使用[旧版](https://greasyfork.org/zh-CN/scripts/400250)遇到的问题不应该来[新版](https://github.com/master-of-forums/master-of-forums)仓库反馈。

**Comment by Marukon** [comment]
抱歉大佬，是我弄混了
