### ISSUE TITLE
在 txrjy.com 无法发表帖子，关闭以后正常

### ISSUE THREAD

**Issue by Loukky** [master-of-forums/master-of-forums#8]
详见图
https://imgur.loukky.com/imgs/2021/10/b9e2f1e6b1b5e15e.png

**Comment by Loukky** [comment]
这个论坛可以直接注册账号吧好像

**Comment by upsups** [comment]
重新安装[论坛大师](https://github.com/master-of-forums/master-of-forums#readme)
